### PR TITLE
Document boxes inputs, outputs, metrics

### PR DESCRIPTION
**Pull request by mabelzhang**
Documents inputs, outputs, and error metrics, for the boxes test.

The actual change is just one section at the end of the Python Notebook file, lines 410-438 in the diff.

:thinking: The JSON changed a ton, probably because the file was updated from v3 to v4 when I open it in Jupyter Notebook.
It [looks like](https://blog.reviewnb.com/jupyter-notebook-github-guide/#how-can-i-track-changes-in-notebooks
) something like ReviewNB can be installed as a GitHub app in the repo, to review Notebook diffs easier.

### CODE REVIEW

**Comment by scpeters** [comment]
I think the inputs could be specified nicely as a markdown table

Parameter                    | Type    | Description
---------------------------- | ------- | -----------
Physics engine               | string  | `ode`, `bullet`, `simbody`, or `dart`
Time step in simulation loop | double  | units of seconds
Model count                  | integer | the number of boxes to spawn
Use collision or not         | Boolean |
Simple or Complex scenario.  | Boolean |

**Comment by scpeters** [comment]
## Metrics

Metric                 | Type     | Description
-----------------------| -------- | -----------
Linear position error  | 3-vector | units of meters
Linear velocity error  | 3-vector | units of meters / second
Angular position error | 3-vector | units of radians
Angular velocity error | 3-vector | units of radians / second
Energy error           | double.  | units of J

~~~
Metric                 | Type     | Description
-----------------------| -------- | -----------
Linear position error  | 3-vector | units of meters
Linear velocity error  | 3-vector | units of meters / second
Angular position error | 3-vector | units of radians
Angular velocity error | 3-vector | units of radians / second
Energy error           | double.  | units of J
~~~

**Comment by scpeters** [comment]
## Additional outputs

Metric                 | Type   | Description
-----------------------| ------ | -----------
Duration in wall time  | double | units of seconds
Duration in sim time   | double | units of seconds
Duration ratio         | double | wall duration divided by sim duration

~~~
Metric                 | Type   | Description
-----------------------| ------ | -----------
Duration in wall time  | double | units of seconds
Duration in sim time   | double | units of seconds
Duration ratio         | double | wall duration divided by sim duration
~~~

**Comment by mabelzhang** [comment]
Tables are now used in [574ebc3](https://github.com/scpeters/benchmark/pull/7/commits/574ebc3eba7cbedc935ebdc635d05b2da39a66da)

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
thanks!

**Pull request merged**
